config/routes.rb
BetaNyc::Application.routes.draw do
  resources :events
  resources :projects

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home' 

  match "about" => "static_pages#about"
  match "mission" => "static_pages#mission"
  match "projects" => "static_pages#projects"
  match "events" => "static_pages#events"
  match "volunteer" => "users#new"
  match 'signup'  => 'users#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :cellphone, :email, :githandle, :name, :password, :password_confirmation
  has_secure_password
  has_many :projects
  has_many :events

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name,  presence: true, length: { maximum: 50 }
  validates :githandle,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: :destroy

  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(page: params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @projects = @user.projects.paginate(page: params[:page])
    @events = @user.events.paginate(page: params[:page])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        # Tell the UserMailer to send a welcome Email after save
        UserMailer.welcome_email(@user).deliver
        
        sign_in @user
        format.html { redirect_to @user, notice: 'Welcome to the Beta Brigade!' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'Profile updated.' }
        format.json { head :no_content }
        sign_in @user
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id]).destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 48 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    link_to(image_tag(gravatar_url, alt: user.name, class: "gravatar"), user)
  end
end

app/views/users/_form.html.haml
= form_for @user, {:html=>{:class=>"form-horizontal"}} do |f|
  = render 'shared/error_messages', object: f.object
  .field.control-group
    .control-label
      = f.label :name
    .controls
      = f.text_field :name
  .field.control-group
    .control-label
      = f.label :email
    .controls
      = f.text_field :email
  .field.control-group
    .control-label
      = f.label :githandle
    .controls
      = f.text_field :githandle
  .field.control-group
    .control-label
      = f.label :cellphone
    .controls
      = f.text_field :cellphone
  %hr/
  .field.control-group
    .control-label
      = f.label :password
    .controls
      = f.password_field :password
  .field.control-group
    .control-label
      = f.label :password_confirmation
    .controls
      = f.password_field :password_confirmation
  .action.control-group
    .controls
      = f.submit "Submit", {:class=>"btn-blue"}

app/views/users/_user.html.haml
%li
  = gravatar_for user
  = link_to user.name, user
  -if current_user.admin? && !current_user?(user)
    =link_to "delete", user, method: :delete, data: { confirm: "Are you sure?" }

app/views/users/edit.html.haml
%h1 Update Profile
= gravatar_for @user
%a{:href=>"http://gravatar.com/emails"} change
= render 'form'

app/views/users/index.html.haml
.main
  .row-fluid
    .span8
      .mainheader
        = link_to "Join Now!", signup_path, {:class=>"btn-blue pull-right"}
        %h1 Beta Brigade
      .maininner
        %p People need to hear what I have to say. I believe we will elect a new President in 2012. It is tragic what we do in the poorest neighborhoods. Kill jobs and lead to a recession, force people off of work and onto unemployment and will actually increase the deficit. We exercise a no-fly zone this evening.
        %p People need to hear what I have to say. People need to hear what I have to say. But for the momoment it's a bit like watching American Idol. We have the newest guest star. People need to hear what I have to say. Nuts. A drug addict.
    .span4
      =image_tag "betabrigade.jpg"
.main
  .mainheader
    %h1 Members
  .maininner
    = will_paginate
    %ul.users
      = render @users
    = will_paginate

app/views/users/new.html.haml
.main
  .maininner
    .row-fluid
      .span6
        %h1 WE WANT YOU
        = image_tag("logo.png", :class=>"pull-left")
        %p This is our time. What else is there to guide us? We seek a new way forward, based on mutual interest and mutual respect. While we breathe, we will hope. This is our time. We can do that. America, this is our moment. For that is the true genius of America - that America can change.
      .span6
        = render :partial => 'users/form'

app/views/users/show.html.haml
.row-fluid
  %aside.main.span4
    .maininner
      = gravatar_for @user
      %h1 #{@user.name}
      %h3 #{@user.email}
      %h3 #{@user.githandle}
      %h3 #{@user.cellphone}
      -if current_user?(@user)
        = link_to 'Edit My Profile', edit_user_path(@user), {:class => "btn"} 
      %section
        -if current_user?(@user)
          = link_to "Create a New Project", new_project_path, {:class=>"btn btn-primary"}
        -if current_user?(@user) && current_user.admin?
          = link_to "Create a New Event", new_event_path, {:class=>"btn btn-primary"}
  .span8
    -if @user.events.any?
      %section.main
        .mainheader.grey
          %h3 Events (#{@user.events.count})
        .maininner
          %ul
            = render @events
    -if @user.projects.any?
      %section.main
        .mainheader.blue
          %h3 Projects (#{@user.projects.count})
        .maininner
          %ul
            = render @projects