config/routes.rb
BetaNyc::Application.routes.draw do
  resources :events
  resources :projects

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home' 

  match "about" => "static_pages#about"
  match "mission" => "static_pages#mission"
  match "projects" => "static_pages#projects"
  match "events" => "static_pages#events"
  match "volunteer" => "users#new"
  match 'signup'  => 'users#new'

end

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-error The form contains #{pluralize(object.errors.count, "error")}.
    %ul
      - object.errors.full_messages.each do |msg|
        %li * #{msg}

app/views/shared/_nav.html.haml
.navbar
  .navbar-inner

    %a{:class=>"btn btn-navbar", :data => {:toggle=>"collapse", :target=>"nav-collapse"}}
      %span{:class=>"icon-bar"}
      %span{:class=>"icon-bar"}
      %span{:class=>"icon-bar"}
    .nav-collapse.collapse
      %ul.nav
        %li 
          =link_to 'About', about_path
        %li
          =link_to "Projects", projects_path
        %li
          =link_to "Events", events_path
        %li
          =link_to "Volunteer", volunteer_path
        %li
          =link_to "Beta Brigade", users_path

app/views/shared/_session.html.haml
- if signed_in?
  = gravatar_for current_user
  = link_to "Sign out", signout_path, method: "delete"
- else
  = link_to "Sign In", signin_path
  |
  = link_to "Sign Up", signup_path

app/views/shared/_social.html.haml
=link_to(image_tag("email-48.png", :class=>"red"), "mailto:betanyc@gmail.com")
=link_to(image_tag("facebook-48.png", :class=>"blue"), "https://www.facebook.com/OpenNYforum")
=link_to(image_tag("twitter-48.png", :class=>"grey"), "https://twitter.com/OpenNYforum")
=link_to(image_tag("github-48.png", :class=>"red"), "https://github.com/openNY/")

app/views/shared/_user_info.html.haml
%a{:href=>"#{user_path(current_user)}"}
  = gravatar_for current_user
%h1 #{current_user.name}
%span
  = link_to "view my profile", current_user
%span
  =pluralize(current_user.projects.count, "project")