config/routes.rb
BetaNyc::Application.routes.draw do
  resources :events
  resources :projects

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home' 

  match "about" => "static_pages#about"
  match "mission" => "static_pages#mission"
  match "projects" => "static_pages#projects"
  match "events" => "static_pages#events"
  match "volunteer" => "users#new"
  match 'signup'  => 'users#new'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :description, :location, :name, :when, :meetup_url, :project_id
  belongs_to :user

  validates :name, presence: true, length: { maximum: 50 }
  validates :user_id, presence: true

  default_scope order: 'events.created_at DESC'
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :signed_in_user, only: [:create, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.paginate(page: params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @user = User.find(@event.user_id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.build(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.haml
%li
  %br/
  .rsvp 
    .date
      %span.day #{event.when.strftime('%d')}
      %br/
      %span.month #{event.when.strftime('%B')}
    = link_to "RSVP", event.meetup_url, {:target=>"_blank", :class=>"btn-red"}
    -if current_user?(event.user)
      %span.options
        =link_to "delete", event, method: :delete,
                                  data: { confirm: "Are you sure?" },
                                  title: event.name
        |
        =link_to "edit", edit_event_path(event)
  .info
    = link_to event.name, event, {:class=>"unit-title"}
    %p.time #{event.when.strftime('%H:%M')}
    %p Location: #{event.location}
    %p #{event.description}

app/views/events/_form.html.haml
= form_for @event, {:html=>{:class=>"form-horizontal"}} do |f|
  = render 'shared/error_messages', object: f.object
  .field.control-group
    .control-label
      = f.label :name
    .controls
      = f.text_field :name
  .field.control-group
    .control-label
      = f.label :meetup_url
    .controls
      = f.text_field :meetup_url
  .field.control-group
    .control-label
      = f.label :location
    .controls
      = f.text_field :location
  .field.control-group
    .control-label
      = f.label :when
    .controls
      = f.datetime_select :when
  .field.control-group
    .control-label
      = f.label :description
    .controls
      = f.text_area :description
  .action.control-group
    .controls
      = f.submit "Submit", {:class=>"btn-blue"}

app/views/events/edit.html.haml
%h1 Edit event
= render 'form'

app/views/events/index.html.haml
.main
  .mainheader
    =link_to "View Events on Meetup.com", "http://www.meetup.com/openny/", {:class=>"btn-blue pull-right"}
    %h1 Beta NYC Events
  .maininner
    = will_paginate
    %ul.events
      = render @events
    = will_paginate

app/views/events/new.html.haml
%h1 New event
= render 'form'

app/views/events/show.html.haml
.main
  .maininner
    %h1
      = link_to @event.name, @event
    .rsvp 
      .date
        %span.day #{@event.when.strftime('%d')}
        %br/
        %span.month #{@event.when.strftime('%B')}
      = link_to "RSVP", @event.meetup_url, {:target=>"_blank", :class=>"btn-red"}
      -if current_user?(@event.user)
        %span.options
          =link_to "delete", @event, method: :delete,
                                      data: { confirm: "Are you sure?" },
                                      title: @event.name
          |
          =link_to "edit", edit_event_path(@event)
    %p #{@event.when.strftime('%H:%M')}
    %p Location: #{@event.location}
    %p
      Contact:
      = link_to @user.name, @user

    %p #{@event.description}