config/routes.rb
BetaNyc::Application.routes.draw do
  resources :events
  resources :projects

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home' 

  match "about" => "static_pages#about"
  match "mission" => "static_pages#mission"
  match "projects" => "static_pages#projects"
  match "events" => "static_pages#events"
  match "volunteer" => "users#new"
  match 'signup'  => 'users#new'

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :name, :url
  belongs_to :user

  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 50 }

  default_scope order: 'projects.created_at DESC'
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :signed_in_user, only: [:create, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.paginate(page: params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    @user = User.find(@project.user_id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.build(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= form_for(@project) do |f| 
  = render 'shared/error_messages', object: f.object
  .field.control-group
    .control-label
      = f.label :name
    .controls
      = f.text_field :name
  .field.control-group
    .control-label
      = f.label :description
    .controls
      = f.text_area :description
  .field.control-group
    .control-label
      = f.label :url
    .controls
      = f.text_field :url
  .action.control-group
    .controls
      = f.submit "Submit", {:class=>"btn-blue"}

app/views/projects/_project.html.haml
%li
  = link_to project.name, project, {:class=>"unit-title"}
  -if current_user?(project.user)
    %span.options
      =link_to "delete", project, method: :delete,
                                data: { confirm: "Are you sure?" },
                                title: project.name
      |
      =link_to "edit", edit_project_path(project)
  %p #{project.description}

app/views/projects/edit.html.haml
.main
  %h1 Editing project
  = render 'form'

app/views/projects/index.html.haml
.main
  .mainheader
    =link_to "View Projects on Github", "http://www.github.com/openny/", {:class=>"btn-blue pull-right"}
    %h1 Brigade Projects
  .maininner
    = will_paginate
    %ul
      = render @projects
    = will_paginate

app/views/projects/new.html.haml
%h1 New project
= render 'form'

app/views/projects/show.html.haml
.main
  .maininner
    %h1
      = link_to @project.name, @project
    -if current_user?(@user)
      .options
        =link_to "delete", @project, method: :delete,
                                      data: { confirm: "Are you sure?" },
                                      title: @project.name
        |
        =link_to "edit", edit_project_path(@project)
    %a{:href=>"#{@project.url}"} website
    %p #{@project.description}
    %p Contact
    = gravatar_for @user
    = link_to @user.name, @user, {:class=>"user"}